[package]
name = "alpen-faucet"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [".", "utils/html-solver"]

[dependencies]
alloy = { version = "0.3.5", features = ["std", "rpc-client-ws", "network", "signers", "signer-local", "providers", "rpc-types"] }
arrayvec = "0.7.6"
axum = { version = "0.7.5", features = ["http2"] }
axum-client-ip = "0.6.0"
axum-macros = "0.4.1"
bdk_esplora = { version = "0.18.0", features = [
  "async-https",
  "async-https-rustls",
], default-features = false }
bdk_wallet = { version = "1.0.0-beta.4", features = ["rusqlite"] }
colored = "2.1.0"
concurrent-map = "5.0.37"
config = { version = "0.14.0", features = ["toml"], default-features = false }
parking_lot = "0.12.3"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sha2 = { version = "0.10.8", features = ["asm", "loongarch64_asm"] }
terrors = "0.3.0"
tokio = { version = "1.40.0", features = [
  "macros",
  "net",
  "parking_lot",
  "rt-multi-thread",
  "time",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "parking_lot"] }
