[package]
name = "faucet-api"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
axum = { version = "0.7.5", features = ["http2"] }
concurrent-map = "5.0.37"
parking_lot = "0.12.3"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
sha2 = { version = "0.10.8", features = ["asm", "loongarch64_asm"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
