host = "127.0.0.1"
port = 3000
ip_src = "ConnectInfo"
seed_file = "faucet.seed"
sqlite_file = "faucet.sqlite"
network = "signet"
esplora = "https://electrs.018235aabb3fe7.stratabtc.org"
l2_http_endpoint = "https://stratareth.018235aabb3fe7.stratabtc.org"
sats_per_claim = 1_002_000_000
pow_difficulty = 19
