host = "127.0.0.1"
port = 3000
ip_src = "ConnectInfo"
seed_file = "faucet.seed"
sqlite_file = "faucet.sqlite"
network = "signet"
esplora = "https://esplora.testnet-staging.stratabtc.org"
l2_http_endpoint = "https://rpc.testnet-staging.stratabtc.org"
l1_sats_per_claim = 1001000000
l2_sats_per_claim = 10000000

[l1_pow]
min_balance = 50000000000  # 500 BTC
min_difficulty = 17

[l2_pow]
min_balance = 10000000000  # 100 BTC
min_difficulty = 17        # Slightly easier for L2
