host = "127.0.0.1"
port = 3000
ip_src = "ConnectInfo"
seed_file = "faucet.seed"
sqlite_file = "faucet.sqlite"
network = "signet"
esplora = "https://esploraapi.devnet-annapurna.stratabtc.org"
l2_http_endpoint = "https://stratareth.devnet-annapurna.stratabtc.org"
l1_sats_per_claim = 1_000_001_000
l2_sats_per_claim = 1_000_001_000
pow_difficulty = 19
