unstable_features = true
wrap_comments = true
edition = "2021"
use_field_init_shorthand = true
format_code_in_doc_comments = true
max_width = 100
# rewrite_imports = true
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
